language: node_js
node_js:
  - "16.15.1"
cache:
  directories:
  - node_modules
script:
  - npm run build
before_deploy:
  - "sed -i '/build.html/d' .gitignore"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master